version: "3"
services:
  php:
    build:
      context: dockerfile/php
      dockerfile: dockerfile
      args:
        PHPREDIS_VERSION: 4.3.0
        XDEBUG_VERSION: 2.7.0
        AMQP_VERSION: 1.9.4
        MCRYPT_VERSION: 1.0.2
        MONGODB_VERSION: 1.5.3
        PHALCON_VERSION: 3.4.3
        SWOOLE_VERSION: 4.3.1
        PHPUNIT_VERSION: 8
    container_name: dnmp-php
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      - dnmp
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/data/htdocs
      - ./conf/hosts:/etc/hosts:rw
  nginx:
    build:
      context: dockerfile/nginx
      dockerfile: dockerfile
    container_name: dnmp-nginx
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    networks:
      - dnmp
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/data/htdocs
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/vhost:/etc/nginx/vhost
    depends_on:
      - php
  mysql:
    build:
      context: dockerfile/mysql
      dockerfile: dockerfile
      args:
        MYSQL_VERSION: 5.7
    container_name: dnmp-mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - dnmp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "RainyDB2018"
    volumes:
      - ${MYSQL_DATA_ROOT}:/var/lib/mysql
  phpmyadmin:
    build:
      context: ./dockerfile/phpmyadmin
      dockerfile: dockerfile
    ports:
      - 8080:80
    networks:
      - dnmp
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    container_name: dnmp-phpmyadmin
    restart: always
  redis:
    build:
      context: ./dockerfile/redis
      dockerfile: dockerfile
      args:
        REDIS_VERSION: 4
    ports:
      - "6379:6379"
    container_name: docker-lnmp-redis
    networks:
      - dnmp
    restart: always
networks:
  dnmp: